### PR TITLE
minor: fix numbering in prompt

### PR DESCRIPTION
**Pull request by dooart**

### CODE REVIEW

**Comment by rtaori** [comment]
Hi, thanks for noticing this issue! You are correct; we actually ran the data generation process with the incorrect numbering. To keep things consistent with our released data, we are not going to merge this PR, but I will edit the README next to the data generation process to refer readers here for the future.

**Comment by LeopoldACC** [comment]
Hi, @rtaori, Thanks for your sharing.
I find that @dooart 's answer has been deleted. What's problem of the numbering and how to fix it in the code? Thanks!

**Comment by shogoinadomi** [comment]
Hi, a very minor mistake exists. "necssary"→"necessary"

**Comment by DreamInvoker** [comment]
Hi, another very minor mistake exists. "instrucitons"→"instructions"

**Pull request closed without merging**
